
export const BIBLE_INDEX = {
  books: [
    { id: 'genesis', name: 'Utpatti (Genesis)', chapters: 50, type: 'OT' },
    { id: 'exodus', name: 'Nirgaman (Exodus)', chapters: 40, type: 'OT' },
    { id: 'leviticus', name: 'Levyavyavastha (Leviticus)', chapters: 27, type: 'OT' },
    { id: 'numbers', name: 'Ganan (Numbers)', chapters: 36, type: 'OT' },
    { id: 'deuteronomy', name: 'Vyavastha (Deuteronomy)', chapters: 34, type: 'OT' },
    { id: 'joshua', name: 'Yashu (Joshua)', chapters: 24, type: 'OT' },
    { id: 'judges', name: 'Nyayiyo (Judges)', chapters: 21, type: 'OT' },
    { id: 'ruth', name: 'Rut (Ruth)', chapters: 4, type: 'OT' },
    { id: '1-samuel', name: '1 Samuel', chapters: 31, type: 'OT' },
    { id: '2-samuel', name: '2 Samuel', chapters: 24, type: 'OT' },
    { id: '1-kings', name: '1 Raja (1 Kings)', chapters: 22, type: 'OT' },
    { id: '2-kings', name: '2 Raja (2 Kings)', chapters: 25, type: 'OT' },
    { id: '1-chronicles', name: '1 Itihas (1 Chronicles)', chapters: 29, type: 'OT' },
    { id: '2-chronicles', name: '2 Itihas (2 Chronicles)', chapters: 36, type: 'OT' },
    { id: 'ezra', name: 'Ezra', chapters: 10, type: 'OT' },
    { id: 'nehemiah', name: 'Nehemiah', chapters: 13, type: 'OT' },
    { id: 'esther', name: 'Esther', chapters: 10, type: 'OT' },
    { id: 'job', name: 'Ayyub (Job)', chapters: 42, type: 'OT' },
    { id: 'psalms', name: 'Bhajan Sanhita (Psalms)', chapters: 150, type: 'OT' },
    { id: 'proverbs', name: 'Nitivachan (Proverbs)', chapters: 31, type: 'OT' },
    { id: 'ecclesiastes', name: 'Sabhopadeshak (Ecclesiastes)', chapters: 12, type: 'OT' },
    { id: 'song-of-solomon', name: 'Shrestha Geet (Song of Solomon)', chapters: 8, type: 'OT' },
    { id: 'isaiah', name: 'Yashayah (Isaiah)', chapters: 66, type: 'OT' },
    { id: 'jeremiah', name: 'Yirmayah (Jeremiah)', chapters: 52, type: 'OT' },
    { id: 'lamentations', name: 'Vilap Geet (Lamentations)', chapters: 5, type: 'OT' },
    { id: 'ezekiel', name: 'Hizqiyel (Ezekiel)', chapters: 48, type: 'OT' },
    { id: 'daniel', name: 'Daniel', chapters: 12, type: 'OT' },
    { id: 'hosea', name: 'Hosea', chapters: 14, type: 'OT' },
    { id: 'joel', name: 'Yoel (Joel)', chapters: 3, type: 'OT' },
    { id: 'amos', name: 'Amos', chapters: 9, type: 'OT' },
    { id: 'obadiah', name: 'Obadiah', chapters: 1, type: 'OT' },
    { id: 'jonah', name: 'Yona (Jonah)', chapters: 4, type: 'OT' },
    { id: 'micah', name: 'Mika (Micah)', chapters: 7, type: 'OT' },
    { id: 'nahum', name: 'Nahum', chapters: 3, type: 'OT' },
    { id: 'habakkuk', name: 'Habakkuk', chapters: 3, type: 'OT' },
    { id: 'zephaniah', name: 'Zephaniah', chapters: 3, type: 'OT' },
    { id: 'haggai', name: 'Haggai', chapters: 2, type: 'OT' },
    { id: 'zechariah', name: 'Zechariah', chapters: 14, type: 'OT' },
    { id: 'malachi', name: 'Malachi', chapters: 4, type: 'OT' },
    { id: 'matthew', name: 'Matti (Matthew)', chapters: 28, type: 'NT' },
    { id: 'mark', name: 'Markus (Mark)', chapters: 16, type: 'NT' },
    { id: 'luke', name: 'Luka (Luke)', chapters: 24, type: 'NT' },
    { id: 'john', name: 'Yuhanna (John)', chapters: 21, type: 'NT' },
    { id: 'acts', name: 'Prerit (Acts)', chapters: 28, type: 'NT' },
    { id: 'romans', name: 'Romiyo (Romans)', chapters: 16, type: 'NT' },
    { id: '1-corinthians', name: '1 Kurunthiyo (1 Corinthians)', chapters: 16, type: 'NT' },
    { id: '2-corinthians', name: '2 Kurunthiyo (2 Corinthians)', chapters: 13, type: 'NT' },
    { id: 'galatians', name: 'Galatiyo (Galatians)', chapters: 6, type: 'NT' },
    { id: 'ephesians', name: 'Afisiyo (Ephesians)', chapters: 6, type: 'NT' },
    { id: 'philippians', name: 'Filippiyo (Philippians)', chapters: 4, type: 'NT' },
    { id: 'colossians', name: 'Kulusiyo (Colossians)', chapters: 4, type: 'NT' },
    { id: '1-thessalonians', name: '1 Thissalunikiun (1 Thess)', chapters: 5, type: 'NT' },
    { id: '2-thessalonians', name: '2 Thissalunikiun (2 Thess)', chapters: 3, type: 'NT' },
    { id: '1-timothy', name: '1 Timothiyus (1 Timothy)', chapters: 6, type: 'NT' },
    { id: '2-timothy', name: '2 Timothiyus (2 Timothy)', chapters: 4, type: 'NT' },
    { id: 'titus', name: 'Titus', chapters: 3, type: 'NT' },
    { id: 'philemon', name: 'Philemon', chapters: 1, type: 'NT' },
    { id: 'hebrews', name: 'Ibraniyo (Hebrews)', chapters: 13, type: 'NT' },
    { id: 'james', name: 'Yaqoob (James)', chapters: 5, type: 'NT' },
    { id: '1-peter', name: '1 Patras (1 Peter)', chapters: 5, type: 'NT' },
    { id: '2-peter', name: '2 Patras (2 Peter)', chapters: 3, type: 'NT' },
    { id: '1-john', name: '1 Yuhanna (1 John)', chapters: 5, type: 'NT' },
    { id: '2-john', name: '2 Yuhanna (2 John)', chapters: 1, type: 'NT' },
    { id: '3-john', name: '3 Yuhanna (3 John)', chapters: 1, type: 'NT' },
    { id: 'jude', name: 'Yuda (Jude)', chapters: 1, type: 'NT' },
    { id: 'revelation', name: 'Prakashit Vakya (Revelation)', chapters: 22, type: 'NT' }
  ],
  versions: [
    { id: 'hin_irv', name: 'Hindi (IRV)', lang: 'hi-IN' },
    { id: 'kjv', name: 'English (KJV)', lang: 'en-US' }
  ]
};
