export type BibleBook = {
  id: string;
  usfm: string;
  en: string;
  hi: string;
  chapters: number;
  testament: 'old' | 'new' | 'deuterocanon';
  bollsId: number; 
};

export const BIBLE_BOOKS: BibleBook[] = [
  // OLD TESTAMENT (39 Books)
  { id: "GEN", usfm: "GEN", en: "Genesis", hi: "उत्पत्ति", chapters: 50, testament: "old", bollsId: 1 },
  { id: "EXO", usfm: "EXO", en: "Exodus", hi: "निर्गमन", chapters: 40, testament: "old", bollsId: 2 },
  { id: "LEV", usfm: "LEV", en: "Leviticus", hi: "लैव्यव्यवस्था", chapters: 27, testament: "old", bollsId: 3 },
  { id: "NUM", usfm: "NUM", en: "Numbers", hi: "गिनती", chapters: 36, testament: "old", bollsId: 4 },
  { id: "DEU", usfm: "DEU", en: "Deuteronomy", hi: "व्यवस्थाविवरण", chapters: 34, testament: "old", bollsId: 5 },
  { id: "JOS", usfm: "JOS", en: "Joshua", hi: "यहोशू", chapters: 24, testament: "old", bollsId: 6 },
  { id: "JDG", usfm: "JDG", en: "Judges", hi: "न्यायियों", chapters: 21, testament: "old", bollsId: 7 },
  { id: "RUT", usfm: "RUT", en: "Ruth", hi: "रूत", chapters: 4, testament: "old", bollsId: 8 },
  { id: "1SA", usfm: "1SA", en: "1 Samuel", hi: "१ शमूएल", chapters: 31, testament: "old", bollsId: 9 },
  { id: "2SA", usfm: "2SA", en: "2 Samuel", hi: "२ शमूएल", chapters: 24, testament: "old", bollsId: 10 },
  { id: "1KI", usfm: "1KI", en: "1 Kings", hi: "१ राजा", chapters: 22, testament: "old", bollsId: 11 },
  { id: "2KI", usfm: "2KI", en: "2 Kings", hi: "२ राजा", chapters: 25, testament: "old", bollsId: 12 },
  { id: "1CH", usfm: "1CH", en: "1 Chronicles", hi: "१ इतिहास", chapters: 29, testament: "old", bollsId: 13 },
  { id: "2CH", usfm: "2CH", en: "2 Chronicles", hi: "२ इतिहास", chapters: 36, testament: "old", bollsId: 14 },
  { id: "EZR", usfm: "EZR", en: "Ezra", hi: "एज्रा", chapters: 10, testament: "old", bollsId: 15 },
  { id: "NEH", usfm: "NEH", en: "Nehemiah", hi: "नहेमायाह", chapters: 13, testament: "old", bollsId: 16 },
  { id: "EST", usfm: "EST", en: "Esther", hi: "एस्तेर", chapters: 10, testament: "old", bollsId: 17 },
  { id: "JOB", usfm: "JOB", en: "Job", hi: "अय्यूब", chapters: 42, testament: "old", bollsId: 18 },
  { id: "PSA", usfm: "PSA", en: "Psalms", hi: "भजनसंग्रह", chapters: 150, testament: "old", bollsId: 19 },
  { id: "PRO", usfm: "PRO", en: "Proverbs", hi: "नीतिवचन", chapters: 31, testament: "old", bollsId: 20 },
  { id: "ECC", usfm: "ECC", en: "Ecclesiastes", hi: "सभोपदेशक", chapters: 12, testament: "old", bollsId: 21 },
  { id: "SNG", usfm: "SNG", en: "Song of Solomon", hi: "श्रेष्ठगीत", chapters: 8, testament: "old", bollsId: 22 },
  { id: "ISA", usfm: "ISA", en: "Isaiah", hi: "यशायाह", chapters: 66, testament: "old", bollsId: 23 },
  { id: "JER", usfm: "JER", en: "Jeremiah", hi: "यिर्मयाह", chapters: 52, testament: "old", bollsId: 24 },
  { id: "LAM", usfm: "LAM", en: "Lamentations", hi: "विलापगीत", chapters: 5, testament: "old", bollsId: 25 },
  { id: "EZK", usfm: "EZK", en: "Ezekiel", hi: "यहेजकेल", chapters: 48, testament: "old", bollsId: 26 },
  { id: "DAN", usfm: "DAN", en: "Daniel", hi: "दानिय्येल", chapters: 12, testament: "old", bollsId: 27 },
  { id: "HOS", usfm: "HOS", en: "Hosea", hi: "होशे", chapters: 14, testament: "old", bollsId: 28 },
  { id: "JOL", usfm: "JOL", en: "Joel", hi: "योएल", chapters: 3, testament: "old", bollsId: 29 },
  { id: "AMO", usfm: "AMO", en: "Amos", hi: "आमोस", chapters: 9, testament: "old", bollsId: 30 },
  { id: "OBA", usfm: "OBA", en: "Obadiah", hi: "ओबद्याह", chapters: 1, testament: "old", bollsId: 31 },
  { id: "JON", usfm: "JON", en: "Jonah", hi: "योना", chapters: 4, testament: "old", bollsId: 32 },
  { id: "MIC", usfm: "MIC", en: "Micah", hi: "मीका", chapters: 7, testament: "old", bollsId: 33 },
  { id: "NAM", usfm: "NAM", en: "Nahum", hi: "नहूम", chapters: 3, testament: "old", bollsId: 34 },
  { id: "HAB", usfm: "HAB", en: "Habakkuk", hi: "हबक्कूक", chapters: 3, testament: "old", bollsId: 35 },
  { id: "ZEP", usfm: "ZEP", en: "Zephaniah", hi: "सपन्याह", chapters: 3, testament: "old", bollsId: 36 },
  { id: "HAG", usfm: "HAG", en: "Haggai", hi: "हाग्गै", chapters: 2, testament: "old", bollsId: 37 },
  { id: "ZEC", usfm: "ZEC", en: "Zechariah", hi: "जकर्याह", chapters: 14, testament: "old", bollsId: 38 },
  { id: "MAL", usfm: "MAL", en: "Malachi", hi: "मलाकी", chapters: 4, testament: "old", bollsId: 39 },

  // DEUTEROCANONICAL / APOCRYPHA (15 Books)
  { id: "TOB", usfm: "TOB", en: "Tobit", hi: "तोबियाह", chapters: 14, testament: "deuterocanon", bollsId: 67 },
  { id: "JDT", usfm: "JDT", en: "Judith", hi: "यहूदीत", chapters: 16, testament: "deuterocanon", bollsId: 68 },
  { id: "WIS", usfm: "WIS", en: "Wisdom", hi: "बुद्धि", chapters: 19, testament: "deuterocanon", bollsId: 69 },
  { id: "SIR", usfm: "SIR", en: "Sirach", hi: "सिराख", chapters: 51, testament: "deuterocanon", bollsId: 70 },
  { id: "BAR", usfm: "BAR", en: "Baruch", hi: "बारूक", chapters: 5, testament: "deuterocanon", bollsId: 71 },
  { id: "LJE", usfm: "LJE", en: "Letter of Jeremiah", hi: "यिर्मयाह का पत्र", chapters: 1, testament: "deuterocanon", bollsId: 72 },
  { id: "AZA", usfm: "AZA", en: "Prayer of Azariah", hi: "अजरयाह की प्रार्थना", chapters: 1, testament: "deuterocanon", bollsId: 73 },
  { id: "SUS", usfm: "SUS", en: "Susanna", hi: "सूसाना", chapters: 1, testament: "deuterocanon", bollsId: 74 },
  { id: "BEL", usfm: "BEL", en: "Bel and the Dragon", hi: "बेल और अजगर", chapters: 1, testament: "deuterocanon", bollsId: 75 },
  { id: "1MA", usfm: "1MA", en: "1 Maccabees", hi: "1 मक्काबी", chapters: 16, testament: "deuterocanon", bollsId: 76 },
  { id: "2MA", usfm: "2MA", en: "2 Maccabees", hi: "2 मक्काबी", chapters: 15, testament: "deuterocanon", bollsId: 77 },
  { id: "1ES", usfm: "1ES", en: "1 Esdras", hi: "1 एज्रा", chapters: 9, testament: "deuterocanon", bollsId: 78 },
  { id: "MAN", usfm: "MAN", en: "Prayer of Manasseh", hi: "मनश्शे की प्रार्थना", chapters: 1, testament: "deuterocanon", bollsId: 79 },
  { id: "3MA", usfm: "3MA", en: "3 Maccabees", hi: "3 मक्काबी", chapters: 7, testament: "deuterocanon", bollsId: 80 },
  { id: "4MA", usfm: "4MA", en: "4 Maccabees", hi: "4 मक्काबी", chapters: 18, testament: "deuterocanon", bollsId: 81 },

  // NEW TESTAMENT (27 Books)
  { id: "MAT", usfm: "MAT", en: "Matthew", hi: "मत्ती", chapters: 28, testament: "new", bollsId: 40 },
  { id: "MRK", usfm: "MRK", en: "Mark", hi: "मरकुस", chapters: 16, testament: "new", bollsId: 41 },
  { id: "LUK", usfm: "LUK", en: "Luke", hi: "लूका", chapters: 24, testament: "new", bollsId: 42 },
  { id: "JHN", usfm: "JHN", en: "John", hi: "यूहन्ना", chapters: 21, testament: "new", bollsId: 43 },
  { id: "ACT", usfm: "ACT", en: "Acts", hi: "प्रेरितों के काम", chapters: 28, testament: "new", bollsId: 44 },
  { id: "ROM", usfm: "ROM", en: "Romans", hi: "रोमियों", chapters: 16, testament: "new", bollsId: 45 },
  { id: "1CO", usfm: "1CO", en: "1 Corinthians", hi: "१ कुरिन्थियों", chapters: 16, testament: "new", bollsId: 46 },
  { id: "2CO", usfm: "2CO", en: "2 Corinthians", hi: "२ कुरिन्थियों", chapters: 13, testament: "new", bollsId: 47 },
  { id: "GAL", usfm: "GAL", en: "Galatians", hi: "गलातियों", chapters: 6, testament: "new", bollsId: 48 },
  { id: "EPH", usfm: "EPH", en: "Ephesians", hi: "इफिसियों", chapters: 6, testament: "new", bollsId: 49 },
  { id: "PHP", usfm: "PHP", en: "Philippians", hi: "फिलिप्पियों", chapters: 4, testament: "new", bollsId: 50 },
  { id: "COL", usfm: "COL", en: "Colossians", hi: "कुलुस्सियों", chapters: 4, testament: "new", bollsId: 51 },
  { id: "1TH", usfm: "1TH", en: "1 Thessalonians", hi: "१ थिस्सलुनीकियों", chapters: 5, testament: "new", bollsId: 52 },
  { id: "2TH", usfm: "2TH", en: "2 Thessalonians", hi: "२ थिस्सलुनीकियों", chapters: 3, testament: "new", bollsId: 53 },
  { id: "1TI", usfm: "1TI", en: "1 Timothy", hi: "१ तीमुथियुस", chapters: 6, testament: "new", bollsId: 54 },
  { id: "2TI", usfm: "2TI", en: "2 Timothy", hi: "२ तीमुथियुस", chapters: 4, testament: "new", bollsId: 55 },
  { id: "TIT", usfm: "TIT", en: "Titus", hi: "तीतुस", chapters: 3, testament: "new", bollsId: 56 },
  { id: "PHM", usfm: "PHM", en: "Philemon", hi: "फिलेमोन", chapters: 1, testament: "new", bollsId: 57 },
  { id: "HEB", usfm: "HEB", en: "Hebrews", hi: "इब्रानियों", chapters: 13, testament: "new", bollsId: 58 },
  { id: "JAS", usfm: "JAS", en: "James", hi: "याकूब", chapters: 5, testament: "new", bollsId: 59 },
  { id: "1PE", usfm: "1PE", en: "1 Peter", hi: "१ पतरस", chapters: 5, testament: "new", bollsId: 60 },
  { id: "2PE", usfm: "2PE", en: "2 Peter", hi: "२ पतरस", chapters: 3, testament: "new", bollsId: 61 },
  { id: "1JN", usfm: "1JN", en: "1 John", hi: "१ यूहन्ना", chapters: 5, testament: "new", bollsId: 62 },
  { id: "2JN", usfm: "2JN", en: "2 John", hi: "२ यूहन्ना", chapters: 1, testament: "new", bollsId: 63 },
  { id: "3JN", usfm: "3JN", en: "3 John", hi: "३ यूहन्ना", chapters: 1, testament: "new", bollsId: 64 },
  { id: "JUD", usfm: "JUD", en: "Judude", hi: "यहूदा", chapters: 1, testament: "new", bollsId: 65 },
  { id: "REV", usfm: "REV", en: "Revelation", hi: "प्रकाशितवाक्य", chapters: 22, testament: "new", bollsId: 66 }
];
