
export const BIBLE_BOOKS = [
  // OLD TESTAMENT
  { id: 'GEN', en: 'Genesis', hi: 'उत्पत्ति', chapters: 50, testament: 'old', usfm: 'GEN' },
  { id: 'EXO', en: 'Exodus', hi: 'निर्गमन', chapters: 40, testament: 'old', usfm: 'EXO' },
  { id: 'LEV', en: 'Leviticus', hi: 'लैव्यव्यवस्था', chapters: 27, testament: 'old', usfm: 'LEV' },
  { id: 'NUM', en: 'Numbers', hi: 'गिनती', chapters: 36, testament: 'old', usfm: 'NUM' },
  { id: 'DEU', en: 'Deuteronomy', hi: 'व्यवस्थाविवरण', chapters: 34, testament: 'old', usfm: 'DEU' },
  { id: 'JOS', en: 'Joshua', hi: 'यहोशू', chapters: 24, testament: 'old', usfm: 'JOS' },
  { id: 'JDG', en: 'Judges', hi: 'न्यायियों', chapters: 21, testament: 'old', usfm: 'JDG' },
  { id: 'RUT', en: 'Ruth', hi: 'रूत', chapters: 4, testament: 'old', usfm: 'RUT' },
  { id: '1SA', en: '1 Samuel', hi: '1 शमूएल', chapters: 31, testament: 'old', usfm: '1SA' },
  { id: '2SA', en: '2 Samuel', hi: '2 शमूएल', chapters: 24, testament: 'old', usfm: '2SA' },
  { id: '1KI', en: '1 Kings', hi: '1 राजा', chapters: 22, testament: 'old', usfm: '1KI' },
  { id: '2KI', en: '2 Kings', hi: '2 राजा', chapters: 25, testament: 'old', usfm: '2KI' },
  { id: '1CH', en: '1 Chronicles', hi: '1 इतिहास', chapters: 29, testament: 'old', usfm: '1CH' },
  { id: '2CH', en: '2 Chronicles', hi: '2 इतिहास', chapters: 36, testament: 'old', usfm: '2CH' },
  { id: 'EZR', en: 'Ezra', hi: 'एज्रा', chapters: 10, testament: 'old', usfm: 'EZR' },
  { id: 'NEH', en: 'Nehemiah', hi: 'नहेम्याह', chapters: 13, testament: 'old', usfm: 'NEH' },
  { id: 'EST', en: 'Esther', hi: 'एस्तर', chapters: 10, testament: 'old', usfm: 'EST' },
  { id: 'JOB', en: 'Job', hi: 'अय्यूब', chapters: 42, testament: 'old', usfm: 'JOB' },
  { id: 'PSA', en: 'Psalms', hi: 'भजन संहिता', chapters: 150, testament: 'old', usfm: 'PSA' },
  { id: 'PRO', en: 'Proverbs', hi: 'नीतिवचन', chapters: 31, testament: 'old', usfm: 'PRO' },
  { id: 'ECC', en: 'Ecclesiastes', hi: 'सभोपदेशक', chapters: 12, testament: 'old', usfm: 'ECC' },
  { id: 'SNG', en: 'Song of Solomon', hi: 'श्रेष्ठगीत', chapters: 8, testament: 'old', usfm: 'SNG' },
  { id: 'ISA', en: 'Isaiah', hi: 'यशायाह', chapters: 66, testament: 'old', usfm: 'ISA' },
  { id: 'JER', en: 'Jeremiah', hi: 'यिर्मयाह', chapters: 52, testament: 'old', usfm: 'JER' },
  { id: 'LAM', en: 'Lamentations', hi: 'विलापगीत', chapters: 5, testament: 'old', usfm: 'LAM' },
  { id: 'EZK', en: 'Ezekiel', hi: 'यहेजकेल', chapters: 48, testament: 'old', usfm: 'EZK' },
  { id: 'DAN', en: 'Daniel', hi: 'दानिय्येल', chapters: 12, testament: 'old', usfm: 'DAN' },
  { id: 'HOS', en: 'Hosea', hi: 'होशे', chapters: 14, testament: 'old', usfm: 'HOS' },
  { id: 'JOL', en: 'Joel', hi: 'योएल', chapters: 3, testament: 'old', usfm: 'JOL' },
  { id: 'AMO', en: 'Amos', hi: 'आमोस', chapters: 9, testament: 'old', usfm: 'AMO' },
  { id: 'OBA', en: 'Obadiah', hi: 'ओबद्याह', chapters: 1, testament: 'old', usfm: 'OBA' },
  { id: 'JON', en: 'Jonah', hi: 'योना', chapters: 4, testament: 'old', usfm: 'JON' },
  { id: 'MIC', en: 'Micah', hi: 'मीका', chapters: 7, testament: 'old', usfm: 'MIC' },
  { id: 'NAM', en: 'Nahum', hi: 'नहूम', chapters: 3, testament: 'old', usfm: 'NAM' },
  { id: 'HAB', en: 'Habakkuk', hi: 'हबक्कूक', chapters: 3, testament: 'old', usfm: 'HAB' },
  { id: 'ZEP', en: 'Zephaniah', hi: 'सपन्याह', chapters: 3, testament: 'old', usfm: 'ZEP' },
  { id: 'HAG', en: 'Haggai', hi: 'हाग्गै', chapters: 2, testament: 'old', usfm: 'HAG' },
  { id: 'ZEC', en: 'Zechariah', hi: 'जकर्याह', chapters: 14, testament: 'old', usfm: 'ZEC' },
  { id: 'MAL', en: 'Malachi', hi: 'मलाकी', chapters: 4, testament: 'old', usfm: 'MAL' },

  // DEUTEROCANON (Apocrypha)
  { id: 'TOB', en: 'Tobit', hi: 'तोबीत', chapters: 14, testament: 'deuterocanon', usfm: 'TOB' },
  { id: 'JDT', en: 'Judith', hi: 'यहूदीत', chapters: 16, testament: 'deuterocanon', usfm: 'JDT' },
  { id: 'WIS', en: 'Wisdom of Solomon', hi: 'सुलेमान का विवेक', chapters: 19, testament: 'deuterocanon', usfm: 'WIS' },
  { id: 'SIR', en: 'Sirach', hi: 'सीराख', chapters: 51, testament: 'deuterocanon', usfm: 'SIR' },
  { id: 'BAR', en: 'Baruch', hi: 'बारूक', chapters: 6, testament: 'deuterocanon', usfm: 'BAR' },
  { id: '1MA', en: '1 Maccabees', hi: '1 मक्काबी', chapters: 16, testament: 'deuterocanon', usfm: '1MA' },
  { id: '2MA', en: '2 Maccabees', hi: '2 मक्काबी', chapters: 15, testament: 'deuterocanon', usfm: '2MA' },

  // NEW TESTAMENT
  { id: 'MAT', en: 'Matthew', hi: 'मत्ती', chapters: 28, testament: 'new', usfm: 'MAT' },
  { id: 'MRK', en: 'Mark', hi: 'मरकुस', chapters: 16, testament: 'new', usfm: 'MRK' },
  { id: 'LUK', en: 'Luke', hi: 'लूका', chapters: 24, testament: 'new', usfm: 'LUK' },
  { id: 'JHN', en: 'John', hi: 'यूहन्ना', chapters: 21, testament: 'new', usfm: 'JHN' },
  { id: 'ACT', en: 'Acts', hi: 'प्रेरितों के काम', chapters: 28, testament: 'new', usfm: 'ACT' },
  { id: 'ROM', en: 'Romans', hi: 'रोमियों', chapters: 16, testament: 'new', usfm: 'ROM' },
  { id: '1CO', en: '1 Corinthians', hi: '1 कुरिन्थियों', chapters: 16, testament: 'new', usfm: '1CO' },
  { id: '2CO', en: '2 Corinthians', hi: '2 कुरिन्थियों', chapters: 13, testament: 'new', usfm: '2CO' },
  { id: 'GAL', en: 'Galatians', hi: 'गलातियों', chapters: 6, testament: 'new', usfm: 'GAL' },
  { id: 'EPH', en: 'Ephesians', hi: 'इफिसियों', chapters: 6, testament: 'new', usfm: 'EPH' },
  { id: 'PHP', en: 'Philippians', hi: 'फिलिप्पियों', chapters: 4, testament: 'new', usfm: 'PHP' },
  { id: 'COL', en: 'Colossians', hi: 'कुलुस्सियों', chapters: 4, testament: 'new', usfm: 'COL' },
  { id: '1TH', en: '1 Thessalonians', hi: '1 थिस्सलुनीकियों', chapters: 5, testament: 'new', usfm: '1TH' },
  { id: '2TH', en: '2 Thessalonians', hi: '2 थिस्सलुनीकियों', chapters: 3, testament: 'new', usfm: '2TH' },
  { id: '1TI', en: '1 Timothy', hi: '1 तीमुथियुस', chapters: 6, testament: 'new', usfm: '1TI' },
  { id: '2TI', en: '2 Timothy', hi: '2 तीमुथियुस', chapters: 4, testament: 'new', usfm: '2TI' },
  { id: 'TIT', en: 'Titus', hi: 'तीतुस', chapters: 3, testament: 'new', usfm: 'TIT' },
  { id: 'PHM', en: 'Philemon', hi: 'फिलेमोन', chapters: 1, testament: 'new', usfm: 'PHM' },
  { id: 'HEB', en: 'Hebrews', hi: 'इब्रानियों', chapters: 13, testament: 'new', usfm: 'HEB' },
  { id: 'JAS', en: 'James', hi: 'याकूब', chapters: 5, testament: 'new', usfm: 'JAS' },
  { id: '1PE', en: '1 पतरस', hi: '1 पतरस', chapters: 5, testament: 'new', usfm: '1PE' },
  { id: '2PE', en: '2 पतरस', hi: '2 पतरस', chapters: 3, testament: 'new', usfm: '2PE' },
  { id: '1JN', en: '1 यूहन्ना', hi: '1 यूहन्ना', chapters: 5, testament: 'new', usfm: '1JN' },
  { id: '2JN', en: '2 यूहन्ना', hi: '2 यूहन्ना', chapters: 1, testament: 'new', usfm: '2JN' },
  { id: '3JN', en: '3 यूहन्ना', hi: '3 यूहन्ना', chapters: 1, testament: 'new', usfm: '3JN' },
  { id: 'JUD', en: 'Jude', hi: 'यहूदा', chapters: 1, testament: 'new', usfm: 'JUD' },
  { id: 'REV', en: 'Revelation', hi: 'प्रकाशितवाक्य', chapters: 22, testament: 'new', usfm: 'REV' },
];
